FROM centos:7

RUN yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && \
    yum install -y jq

ARG BOOTSTRAP_LICENSE
ARG CONFIG

RUN yum-config-manager --add-repo https://release.memsql.com/$(echo "${CONFIG}" | jq -r .channel)/rpm/x86_64/repodata/memsql.repo && \
    yum install -y \
    singlestore-client-$(echo "${CONFIG}" | jq -r .client) \
    singlestoredb-toolbox-$(echo "${CONFIG}" | jq -r .toolbox) \
    singlestoredb-studio-$(echo "${CONFIG}" | jq -r .studio) && \
    yum clean all

RUN usermod -u 1999 memsql && \
    groupmod -g 1998 memsql

